SignalRCore.Web/Models/Agents.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SignalRCore.Web.Models
{
    public partial class Agents
    {
        public long Id { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Subcounty { get; set; }
        public string Ward { get; set; }
        public string Village { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string TerminalId { get; set; }
        public string PhoneNumber { get; set; }
        public string IdNumber { get; set; }
        public DateTime? DateRegistered { get; set; }
        public DateTime? LastModified { get; set; }
    }
        public class AppUserResult
    {
        public int StatusCode { get; set; }
        public int Message { get; set; }
        public int IsSuccessful { get; set; }
    }

    public class Login
    {
        [Required]
        public string UserName { get; set; }
        [Required]
        public string Password { get; set; }
    }

}

SignalRCore.Web/Models/BulkPayment.cs
namespace SignalRCore.Web.Models
{
    public class BulkPayment
    {
        public long Id { get; set; }
        public int Status { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string IdentificationNo { get; set; }
        public string PhoneNumber { get; set; }
    }
}

SignalRCore.Web/Models/Payments.cs
using System;
using System.Collections.Generic;

namespace SignalRCore.Web.Models
{
    public partial class Payments
    {
        public long Id { get; set; }
        public string PaymentMode { get; set; }
        public string PaymentType { get; set; }
        public string MemberNo { get; set; }
        public string PhoneNo { get; set; }
        public string AccountNo { get; set; }
        public string CardNo { get; set; }
        public decimal? Amount { get; set; }
        public int? Status { get; set; }
        public string DocumentNo { get; set; }
        public string Description { get; set; }
        public DateTime? PaymentDate { get; set; }
        public DateTime? TransactionDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime? DateModified { get; set; }
        public string PaymentName { get; set; }
    }
}

SignalRCore.Web/Controllers/AgentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

using Microsoft.AspNetCore.SignalR;


using Microsoft.AspNetCore.Http;

using System.IO;
using SignalRCore.Web.Models;
using SignalRCore.Web.Repository;
using SignalRCore.Web.Persistence;
using Newtonsoft.Json;

namespace Accounts.Controllers
{
    public class AgentsController : Controller
    {
        public Func<InventoryContext> _contextFactory;




        private readonly IInventoryRepository _repository;

        public AgentsController(IInventoryRepository repository, Func<InventoryContext> context)
        {
            _repository = repository;
            _contextFactory = context;
        }


        public IActionResult Index()
        {


            return View();
        }

        public IActionResult Login()
        {
            return View();
        }
        public IActionResult Create()
        {
            return View();
        }
        public IActionResult ValidateLogin(Login login)
        {

            if (login.UserName == "Admin" & login.Password == "kitui@254")
            {
                return RedirectToAction(actionName: nameof(Dashboard));
            }

            return View("Login");
        }
        public IActionResult Dashboard()
        {


            return View("Dashboard");
        }
        public IActionResult Payments()
        {
            InventoryContext context = new InventoryContext();
            var payments = context.Payments.Select(p => new {p.PaymentName,p.AccountNo, p.Amount, p.Id, p.PaymentDate, p.PhoneNo, p.TransactionDate,p.DocumentNo}).Take(100000).OrderByDescending(e => e.Id);
            string json = null;
            json = JsonConvert.SerializeObject(payments);
            return View("Payments", json);
        }
        public IActionResult Registration()
        {
            var xxx = _contextFactory.Invoke().People.Select(p => new { p.IdentificationNo, p.FirstName, p.LastName, p.Id, p.IdentificationType, p.MemberNo, p.PhoneNumber, p.MemberType }).Take(10000).OrderByDescending(e => e.Id);

            string json = null;// = Newtonsoft.Json.JsonConvert.SerializeObject(_repository.Peoples.Select(p=>new { p.IdentificationNo,p.FirstName,p.MiddleName })).ToList());
            json = JsonConvert.SerializeObject(xxx);
            return View("Registration", json);
        }

        public IActionResult Edit(int id)
        {
            var agent = _contextFactory.Invoke().People.Where(s => s.Id == id).FirstOrDefault();
            return View("Edit", agent);
        }

        [HttpPost]
        public IActionResult Post(People test)
        {
            try
            {
                InventoryContext context = new InventoryContext();
                if (test != null)

                {
                    bool isNew = false;
                    var data = context.People.Where(p => p.Id == test.Id).FirstOrDefault();
                    if (data == null)
                    {
                        data = new People();
                        isNew = true;
                    }
                    data.FirstName = test.FirstName;
                    data.LastName = test.LastName;
                    data.IdentificationNo = test.IdentificationNo;
                    data.PhoneNumber = test.PhoneNumber;
                    data.MemberType = test.MemberType;



                    context.People.UpdateRange(data);

                    context.SaveChanges();
                }
                return RedirectToAction("Registration");
            }
            catch (Exception r)
            {
                return NotFound(r.Message);
            }
        }

        public IActionResult EditPayment(int id)
        {
            var Transaction = _contextFactory.Invoke().Payments.Where(s => s.Id == id).FirstOrDefault();
            return View("EditPayments", Transaction);
        }

        [HttpPost]
        public IActionResult PostPayment(Payments test)
        {
            try
            {
                InventoryContext context = new InventoryContext();
                if (test != null)
                {
                    bool isNew = false;
                    var data = context.Payments.Where(p => p.Id == test.Id).FirstOrDefault();
                    if (data == null)
                    {
                        data = new Payments();
                        isNew = true;
                    }
                    data.AccountNo = test.AccountNo;




                    context.Payments.UpdateRange(data);

                    context.SaveChanges();
                }
                return RedirectToAction("Payments");
            }
            catch (Exception r)
            {
                return NotFound(r.Message);
            }
        }

        public IActionResult MakePayments()
        {
            return View("Create");
        }
        [HttpPost]
        public IActionResult CreatePayment(Payments transaction)
        {
            try
            {
                InventoryContext context = new InventoryContext();
                var Transaction = new Payments()
                {
                    AccountNo = transaction.AccountNo,
                    PhoneNo = transaction.PhoneNo,
                    Amount = transaction.Amount,
                    TransactionDate = transaction.TransactionDate,
                    PaymentDate = transaction.TransactionDate,
                    DateModified = transaction.TransactionDate,
                    DocumentNo = transaction.DocumentNo,
                    Status = transaction.Status,
                    PaymentMode = "Manual",
                    PaymentName = transaction.PaymentName
                };
                context.Payments.Add(Transaction);
                context.SaveChanges();

                return RedirectToAction("Payments");
            }
            catch (Exception e)
            {
                return NoContent();
            }
        }

    }
}

SignalRCore.Web/Views/Agents/BulkPayment.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutAgents.cshtml";
}

<div class="container">
    <div class="row">
        @await Html.PartialAsync("_NavPartial")
        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                <h1 class="h2">Dashboard</h1>
                <div class="btn-toolbar mb-2 mb-md-0">
                    <div class="btn-group mr-2">
                        <button class="btn btn-sm btn-outline-secondary">Share</button>
                        <button class="btn btn-sm btn-outline-secondary">Export</button>
                    </div>
                    <button class="btn btn-sm btn-outline-secondary dropdown-toggle">
                        <span data-feather="calendar"></span>
                        This week
                    </button>
                    <div class="input-group">
                    <input type="text" class="daterange" />
                    <div class="input-group-append">
                    <button id="reportrange" class="btn btn-sm btn-outline-secondary dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown
                        <span data-feather="calendar"></span>
                    </button>
                    <div class="dropdown-menu">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <a class="dropdown-item" href="#">Something else here</a>
                    <div role="separator" class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Separated link</a>
                    </div>
                    </div>
                    </div>
                </div>
            </div>
            <form asp-controller="Agents" asp-action="UploadBulkFile" method="post"
                  enctype="multipart/form-data">

                <input type="file" name="file" />
                <button type="submit">Upload File</button>
            </form>
            @*<canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas>*@
            <h2>Section title</h2>
                <div class="table-responsive">
                    <table class="display table table-striped table-sm">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Id Number</th>
                                <th>First Name</th>
                                <th>Last Name</th>
                                
                                <th>Phone Number</th>
                                <th>Subcounty</th>
                                <th>Ward</th>
                                <th>User Name</th>
                               

                            </tr>
                        </thead>
                        <tbody>
                            

                        </tbody>
                    </table>
                </div>
        </main>
    </div>
</div>

@section Scripts {
   <script type="text/javascript">
       $('.daterange').daterangepicker();
       $(document).ready(function () {
           $('#table_id').DataTable();
       });
</script>
}

SignalRCore.Web/Views/Agents/Create.cshtml
<div class="container">



</div>



@model SignalRCore.Web.Models.Payments
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_LayoutAgents.cshtml";
}
@await Html.PartialAsync("_NavPartial")
@await Html.PartialAsync("_MenuBarPartial")

<div id="page-wrapper">
    <div class="main-page">
        <!--grids-->
        <div class="grids">
            <div class="progressbar-heading grids-heading">
                <h2>Forms</h2>
            </div>

            @using (Html.BeginForm("CreatePayment", "Agents", FormMethod.Post, new { }))
            {
                @Html.ValidationSummary(true)

            <fieldset>
                <legend></legend>
                <div class="editor-label">
                     Name
                </div>
                <div class="editor-field">
                    @Html.TextBoxFor(model => model.PaymentName)

                </div>
                <div class="editor-label">
                    Id Number
                </div>
                <div class="editor-field">
                    @Html.TextBoxFor(model => model.AccountNo)

                </div>
                <div class="editor-label">
                    Amount
                </div>
                <div class="editor-field">
                    @Html.TextBoxFor(model => model.Amount)

                </div>

                <div class="editor-label">
                    Phone Number
                </div>

                <div class="editor-field">
                    @Html.TextBoxFor(model => model.PhoneNo)

                </div>
                <div class="editor-label">
                    Transaction Date
                </div>
                <div class="editor-field">
                    @Html.TextBoxFor(model => model.TransactionDate, "{0:yyyy-MM-dd}", new { type = "date" })

                </div>
                <div class="editor-label">
                    Transaction Code
                </div>
                <div class="editor-field">
                    @Html.TextBoxFor(model => model.DocumentNo)

                </div>







                <p>
                    <input type="submit" value="Update" id="btnsave" />
                </p>
            </fieldset>
            }
            <div>
                @Html.ActionLink("Close", "Dashboard")
            </div>
        </div>
        <!--//grids-->
    </div>
</div>

SignalRCore.Web/Views/Agents/Edit.cshtml
@model SignalRCore.Web.Models.People
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_LayoutAgents.cshtml";
}
@await Html.PartialAsync("_NavPartial")
@await Html.PartialAsync("_MenuBarPartial")

<div id="page-wrapper">
    <div class="main-page">
        <!--grids-->
        <div class="grids">
            <div class="progressbar-heading grids-heading">
                <h2>Forms</h2>
            </div>
            @using (Html.BeginForm("Post", "Agents", FormMethod.Post, new { }))
            {
                @Html.ValidationSummary(true)

            <fieldset>
                <legend></legend>
                <div class="editor-label">
                    ID
                </div>
                <div class="editor-field">
                    @Html.TextBoxFor(model => model.Id, new { @readonly = "readonly" })
                </div>
                <div class="editor-label">
                    Name
                </div>
                <div class="editor-field">
                    @Html.TextBoxFor(model => model.FirstName)
                    @Html.ValidationMessageFor(model => model.FirstName)
                </div>
                <div class="editor-label">
                    Description
                </div>
                <div class="editor-field">
                    @Html.TextBoxFor(model => model.LastName)
                    @Html.ValidationMessageFor(model => model.LastName)
                </div>
                <div class="editor-field">
                    @Html.TextBoxFor(model => model.MiddleName)
                    @Html.ValidationMessageFor(model => model.MiddleName)
                </div>
                <div class="editor-label">
                    Description
                </div>
                <div class="editor-field">
                    @Html.TextBoxFor(model => model.IdentificationType)
                    @Html.ValidationMessageFor(model => model.IdentificationType)
                </div>
                <div class="editor-field">
                    @Html.TextBoxFor(model => model.IdentificationNo)
                    @Html.ValidationMessageFor(model => model.IdentificationNo)
                </div>
                <div class="editor-label">
                    Description
                </div>
                <div class="editor-field">
                    @Html.TextBoxFor(model => model.PhoneNumber)
                    @Html.ValidationMessageFor(model => model.PhoneNumber)
                </div>
                <div class="editor-field">
                    @Html.TextBoxFor(model => model.Status)
                    @Html.ValidationMessageFor(model => model.Status)
                </div>
                

                <p>
                    <input type="submit" value="Update" id="btnsave" />
                </p>
            </fieldset>
            }
            <div>
                @Html.ActionLink("Close", "Index")
            </div>
        </div>
        <!--//grids-->
    </div>
</div>

SignalRCore.Web/Views/Agents/EditPayments.cshtml
@model SignalRCore.Web.Models.Payments
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_LayoutAgents.cshtml";
}
@await Html.PartialAsync("_NavPartial")
@await Html.PartialAsync("_MenuBarPartial")

<div id="page-wrapper">
    <div class="main-page">
        <!--grids-->
        <div class="grids">
            <div class="progressbar-heading grids-heading">
                <h2>Forms</h2>
            </div>

            @using (Html.BeginForm("PostPayment", "Agents", FormMethod.Post, new { }))
            {
                @Html.ValidationSummary(true)

            <fieldset>
                <legend></legend>
                <div class="editor-label">
                    ID
                </div>
                <div class="editor-field">
                    @Html.TextBoxFor(model => model.Id, new { @readonly = "readonly" })
                </div>
                <div class="editor-label">
                    Name
                </div>
                <div class="editor-field">
                    @Html.TextBoxFor(model => model.PaymentName)

                </div>
                <div class="editor-label">
                    Amount
                </div>
                <div class="editor-field">
                    @Html.TextBoxFor(model => model.Amount)

                </div>

                <div class="editor-label">
                    Account No
                </div>
                <div class="editor-field">
                    @Html.TextBoxFor(model => model.AccountNo)

                </div>






                <p>
                    <input type="submit" value="Update" id="btnsave" />
                </p>
            </fieldset>
            }
            <div>
                @Html.ActionLink("Close", "Dashboard")
            </div>
        </div>
        <!--//grids-->
    </div>
</div>

SignalRCore.Web/Views/Agents/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutAgents.cshtml";
}




<div class="container-fluid">
    <div class="row">
        @await Html.PartialAsync("_NavPartial")
        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                <h1 class="h2">Registration</h1>
                <div class="btn-toolbar mb-2 mb-md-0">
                    <div class="input"></div>
                    <button class="btn btn-sm btn-outline-secondary dropdown-toggle">
                        <span data-feather="calendar"></span>
                        This week
                    </button>
                    <div class="calendar"></div>
                </div>
            </div>
            
            <h2>Section title</h2>
                <div class="table-responsive">
                    <table id="example" class="table table-striped table-bordered dt-responsive nowrap" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Id Number</th>
                                <th>First Name</th>
                                <th>Middle Name</th>
                                <th>Last Name</th>
                                <th>Phone Number</th>
                                <th>Subcounty</th>
                                <th>Ward</th>
                                <th>User Name</th>
                                
                                
                               

                            </tr>
                        </thead>
                    </table>
                </div>
        </main>
    </div>
</div>
@section Scripts {
<script type="text/javascript">
        
        $(document).ready(function () {
            $('#example').DataTable({
                "processing": true, // for show progress bar
                "serverSide": true, // for process server side
                "filter": true, // this is for disable filter (search box)
                "orderMulti": false, // for disable multiple column at once
                "ajax": {
                    "url": "/Agents/LoadData",
                    "type": "POST",
                    "datatype": "json"
                },
                "columnDefs":
                [{
                        "targets": [0],
                        "visible": true,
                    "searchable": false
                }
                
                ],
                "columns": [  
                     { "data": "Id", "name": "ID", "autoWidth": true }, 
                      { "data": "IdNumber", "name": "Id Number", "autoWidth": true },  
                      { "data": "FirstName", "name": "First Name", "autoWidth": true },
                      { "data": "MiddleName", "name": "Middle Name", "autoWidth": true },  
                      { "data": "LastName",  "name": "Last Name", "autoWidth": true },  
                      { "data": "PhoneNumber", "name": "Phone Number", "autoWidth": true },  
                      { "data": "SUBCOUNTY", "name": "SUB COUNTY", "autoWidth": true },  
                      { "data": "WARD", "name": "WARD", "autoWidth": true },  
                      { "data": "UserName", "name": "User Name", "autoWidth": true } 
                ] 
            });
        });
       
</script>
}

SignalRCore.Web/Views/Agents/Login.cshtml
@model SignalRCore.Web.Models.Login

@{
    ViewData["Title"] = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Styles {
    <link href="@Url.Content("~/css/site.css")" rel="stylesheet" type="text/css" />
}
<div class="wrapper">
    <form class="form-signin" asp-action="Login">
        <h2 class="form-signin-heading">Please login</h2>
        <input type="text" asp-for="UserName" class="form-control" name="username" placeholder="Email Address" required="" autofocus="" />
        <input type="password" asp-for="Password" class="form-control" name="password" placeholder="Password" required="" />
        <label class="checkbox">
            <input type="checkbox" value="remember-me" id="rememberMe" name="rememberMe"> Remember me
        </label>
        <button class="btn btn-lg btn-primary btn-block" type="submit" asp-controller="Agents" asp-action="ValidateLogin">Login</button>
    </form>
</div>

SignalRCore.Web/Views/Agents/Payments.cshtml
@model string

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutAgents.cshtml";



}



@await Html.PartialAsync("_NavPartial")
@await Html.PartialAsync("_MenuBarPartial")
<div id="page-wrapper">
    <div class="main-page">
        <!--grids-->
        <div class="grids">
            <div class="progressbar-heading grids-heading">
                <h2>Blank Page</h2>
            </div>
            <div class="row mb40">
                <div class="col-md-12">
                    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                        <h1 class="h2">All Payments</h1>
                        <div class="btn-toolbar mb-2 mb-md-0">
                            <div class="btn-group mr-2">
                                <button class="btn btn-sm btn-outline-secondary">Share</button>
                                <button class="btn btn-sm btn-outline-secondary">Export</button>
                            </div>
                            <div class="input"></div>
                            <button class="btn btn-sm btn-outline-secondary dropdown-toggle">
                                <span data-feather="calendar"></span>
                                This week
                            </button>
                            <div class="calendar"></div>
                        </div>
                    </div>

                    @*<canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas>*@
                    <h2>Section title</h2>
                    <div class="table-responsive">
                        <table id="Registration" class="table table-striped table-bordered dt-responsive nowrap" width="100%" cellspacing="0">
                            <thead>
                                <tr>

                                    <th>Phone No</th>
                                    <th>Account No </th>
                                    <th>Card No</th>
                                    <th>Amount</th>
                                    <th>Transaction Date</th>
                                    <th>Transacion Code</th>
                                    <th>Payment Name</th>
                                    <th>Edit</th>







                                </tr>
                            </thead>

                        </table>
                    </div>
                </div>
            </div>

        </div>
        <!--//grids-->

    </div>
</div>

@section Scripts {
    <script src="~/lib/DataTables/media/js/jquery.dataTables.js"></script>
    <script src="~/lib/datatables-bootstrap3/BS3/assets/js/datatables.js"></script>
    <script src="~/lib/signalr/signalr-client-1.0.0-alpha2-final.min.js"></script>

    <script type="text/javascript">

        let startConnection = () => {
            connection.start()
                .then(e => {
                    $("#connetion-status").text("Connection opened");
                    $("#connetion-status").css("color", "green");
                })
                .catch(err => console.log(err));
        };

        let showAgents = (Agent) => {
            $('#Registration').DataTable({

                aaData: Agent,
                aoColumns: [

                    { mDataProp: "PhoneNo" },
                    { mDataProp: "AccountNo" },
                    { mDataProp: "CardNo" },
                    { mDataProp: "Amount"},
                    { mDataProp: "TransactionDate" },
                    { mDataProp: "DocumentNo" },
                    { mDataProp: "PaymentName" },
                    {
                         mRender: function (data, type, row) {
            var linkEdit = '@Html.ActionLink("EditPayment", "EditPayment", new {Id= -1 },new {@class = "btn btn-danger" })';
            linkEdit = linkEdit.replace("-1", row.Id);
            return  linkEdit ;

                         }
                    }

                ]
            });

        };

    //let refreshProductList = (Agent) => {
    //    $('#product').find('option').remove();
    //    products.forEach((product) => {
    //        $('<option/>').val(product.name).html(product.name).appendTo('#product');
    //    });
    //}

        let connection = new signalR.HubConnection(`http://${document.location.host}/inventory`, 'formatType=json&format=text');
        startConnection();
        $.fn.dataTable.ext.errMode = 'none';
        showAgents(@Html.Raw(Model));
        $.fn.dataTable.ext.errMode = 'none';
        connection.onClosed = e => {
            if (e) {
                $("#connetion-status").text("Connection closed " + e);
                $("#connetion-status").css("color", "red");
            }
            else {
                $("#connetion-status").text("Connection closed");
                $("#connetion-status").css("color", "green");
            }
            startConnection();
        };

        connection.on('UpdateAgents', Agent => {
            $('#Registration').DataTable().fnClearTable();
            $('#Registration').DataTable().fnAddData(Agent);

        });

    </script>
}